#!/bin/bash

export MS_BOT_BUILDER_APP_ID=XXXXXXX
export MS_BOT_BUILDER_APP_SECRET=XXXXXXX

export LUIS_ID=XXXXXX
export LUIS_KEY=XXXXXX

export ATHENA_KEY=XXXXXXX
export ATHENA_SECRET=XXXXXXX


export MS_BOT_BUILDER_APP_FIREBASE_APP_URL=XXXXXXX
export MS_BOT_BUILDER_APP_FIREBASE_SECRET=XXXXXXXX